### ISSUE TITLE
dependency checks are disabled for all packages

### ISSUE THREAD

**Issue by rafasc** [jrudess/aurutils-plugins#1]
as suggested in https://github.com/AladW/aurutils/blob/master/contrib/README.md#aur-vercmp-devel, you should be using `--no-ver-shallow` in order to ignore the version comparison restrictions for the vcs packages but keep it for its depenedencies.

https://github.com/jrudess/aurutils-plugins/blob/c950ab2b68229c67bfe14ddd3162e9842c1abc28/lib/aur-update-devel#L22

**Comment by jrudess** [comment]
Ah, thanks for pointing that out!
